#include <array>
#include <glm/gtc/matrix_inverse.hpp>

#include "cube.hpp"

// Data generated by "python scripts/convert_obj.py data/cube.obj"

static const float vertices[] = {
    -0.5, -0.5, 0.5, -0.5, 0.5, 0.5, -0.5, -0.5, -0.5,
    -0.5, 0.5, -0.5, 0.5, -0.5, 0.5, 0.5, 0.5, 0.5,
    0.5, -0.5, -0.5, 0.5, 0.5, -0.5,
};

static const float normals[] = {
    -1.0, -0.0, -0.0, -0.0, -0.0, -1.0, 1.0, -0.0, -0.0,
    -0.0, -0.0, 1.0, -0.0, -1.0, -0.0, -0.0, 1.0, -0.0,
};

static const uint16_t triangles[] = {
    1, 0, 2, 0, 0, 0, 3, 1, 6, 1, 2, 1, 7, 2, 4, 2, 6, 2,
    5, 3, 0, 3, 4, 3, 6, 4, 0, 4, 2, 4, 3, 5, 5, 5, 7, 5,
    1, 0, 3, 0, 2, 0, 3, 1, 7, 1, 6, 1, 7, 2, 5, 2, 4, 2,
    5, 3, 1, 3, 0, 3, 6, 4, 4, 4, 0, 4, 3, 5, 1, 5, 5, 5,
};

void addCube(Buffer &buffer, glm::mat4 &transform, glm::vec<4, unsigned char> &rgba)
{
    // TODO: clean up
    glm::mat3 normalMatrix = glm::inverseTranspose(glm::mat3(transform));
    VertexIndex v0, v1, v2;
    glm::vec4 temp;
    glm::vec3 temp2;
    for (auto i = 0; i < sizeof(triangles) / sizeof(uint16_t); i += 6) {
        uint16_t vi, ni;
        vi = triangles[i];
        ni = triangles[i+1];
        temp = {vertices[vi*3], vertices[(vi*3)+1], vertices[(vi*3)+2], 1.0f};
        temp = transform * temp;
        temp2 = {normals[ni*3], normals[(ni*3)+1], normals[(ni*3)+2]};
        temp2 = glm::normalize(normalMatrix * temp2);
        v0 = addVertex(buffer, {
            {temp.x, temp.y, temp.z},
            {temp2.x, temp2.y, temp2.z},
            {rgba[0], rgba[1], rgba[2], rgba[3]}});
        vi = triangles[i+2];
        ni = triangles[i+3];
        temp = {vertices[vi*3], vertices[(vi*3)+1], vertices[(vi*3)+2], 1.0f};
        temp = transform * temp;
        temp2 = {normals[ni*3], normals[(ni*3)+1], normals[(ni*3)+2]};
        temp2 = glm::normalize(normalMatrix * temp2);
        v1 = addVertex(buffer, {
            {temp.x, temp.y, temp.z},
            {temp2.x, temp2.y, temp2.z},
            {rgba[0], rgba[1], rgba[2], rgba[2]}});
        vi = triangles[i+4];
        ni = triangles[i+5];
        temp = {vertices[vi*3], vertices[(vi*3)+1], vertices[(vi*3)+2], 1.0f};
        temp = transform * temp;
        temp2 = {normals[ni*3], normals[(ni*3)+1], normals[(ni*3)+2]};
        temp2 = glm::normalize(normalMatrix * temp2);
        v2 = addVertex(buffer, {
            {temp.x, temp.y, temp.z},
            {temp2.x, temp2.y, temp2.z},
            {rgba[0], rgba[1], rgba[2], rgba[3]}});
        addTriangle(buffer, v0, v1, v2);
    }
}
